export const ApiConstants = {
    Login: '/login',
    CheckUser: '/check-user',
    Register: '/register',
    VerifyOtp: '/otp-verify',
    ResendOtp: '/resend-otp',
    ForgotPassword: '/forgot-password',
    GetMobilityEquipments: '/get-mobility-equipments',
    GetTransferLevels: '/get-transfer-levels',
    GetProfile: '/get-profile',
    ResetPassword: '/reset-password',
    MobileVerification: '/resend-mobile-otp',
    ProfileSetup: '/profile-setup',
    SetupProfile: '/profile-setup',
    UpdateNotificationStatus: '/update-notification',
    UpdateProfileImage: '/upload-profile-image',
    SocialLogin: '/social-login',
    DeleteAccount: '/delete-account',
    PrivacyPolicy: '/privacy-policy',
}