export const Images ={
    LOGO_LARGE:'images/logo-large.svg',
    FB_ICON:'images/fb-icon.svg',
    GOOGLE_ICON:'images/google-icon.svg',
    APPLE_ICON:'images/apple-icon.svg',
    GET_RIDE_IMG:'images/get-rideImg.png',
    CURV_IMG_1:'images/curv-img-1.png',
    CURV_IMG_2:'images/curv-img-2.png',
    UserImg:'images/user-img.png',
    UserImg2:'images/user-img-2.png',
    DeleteAccImg:'images/delete-img.svg',
    Star: 'images/star.svg',
    StarOutline: 'images/star-outline.svg',
    VhImg: 'images/vh-img.svg',
    AseImg: 'images/ase-img.png',
    MailImg: 'images/mail-img.svg',
    SuccessMark: 'images/success-mark.png',
    RideTypeImg1: 'images/rt-1.png',              
    RideTypeImg2: 'images/rt-2.png',              
    RideTypeImg3: 'images/rt-3.png',              
    RideTypeImg4: 'images/rt-4.png', 
    ExclamationMark: 'images/exclamation-mark.svg',      
    LocationIconRed: 'images/location-red.svg',
    DownloadImgIcon: 'images/download-icon-img.svg',
    MsgImgIcon: 'images/msg-icon-img.svg',
    GetHelpImg: 'images/get-help-img.svg',
    CarImg: 'images/car-img.png',
    VanImg: 'images/van.svg',
    ChatImg: 'images/chat-img.svg',
    ShortLogo:'images/short-logo.svg',
    LogoPart1:'images/logo-part-1.svg',
    LogoPart2:'images/logo-part-2.svg',

}