
// Sign in 
export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

// Forgot password 
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

// Reset password 
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

// Sign up 
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// Get Profile
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

//Logout
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

//Change Password
export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL";

//Send Username Password On Mail
export const USER_SEND_MAIL_REQUEST = "USER_SEND_MAIL_REQUEST";
export const USER_SEND_MAIL_SUCCESS = "USER_SEND_MAIL_SUCCESS";
export const USER_SEND_MAIL_FAIL = "USER_SEND_MAIL_FAIL";

//Update Profile
export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";



//Get CMS Pages
export const CMS_PAGE_REQUEST = "CMS_PAGE_REQUEST";
export const CMS_PAGE_SUCCESS = "CMS_PAGE_SUCCESS";
export const CMS_PAGE_FAIL = "CMS_PAGE_FAIL";


//Add Kyc
export const ADD_KYC_REQUEST = "ADD_KYC_REQUEST";
export const ADD_KYC_SUCCESS = "ADD_KYC_SUCCESS";
export const ADD_KYC_FAIL = "ADD_KYC_FAIL";

//Verify Email Phone
export const VERIFY_EMAIL_PHONE_REQUEST = "VERIFY_EMAIL_PHONE_REQUEST";
export const VERIFY_EMAIL_PHONE_SUCCESS = "VERIFY_EMAIL_PHONE_SUCCESS";
export const VERIFY_EMAIL_PHONE_FAIL = "VERIFY_EMAIL_PHONE_FAIL";
