
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_GAME_REQUEST = 'GET_GAME_REQUEST';
export const GET_GAME_FAIL = 'GET_GAME_FAIL';

export const GET_GAME_DETAILS_SUCCESS = 'GET_GAME_DETAILS_SUCCESS';
export const GET_GAME_DETAILS_REQUEST = 'GET_GAME_DETAILS_REQUEST';
export const GET_GAME_DETAILS_FAIL = 'GET_GAME_DETAILS_FAIL';

export const GET_GAME_LIST_SUCCESS = 'GET_GAME_LIST_SUCCESS';
export const GET_GAME_LIST_REQUEST = 'GET_GAME_LIST_REQUEST';
export const GET_GAME_LIST_FAIL = 'GET_GAME_LIST_FAIL';

export const GET_TOP_GAME_LIST_SUCCESS = 'GET_TOP_GAME_LIST_SUCCESS';
export const GET_TOP_GAME_LIST_REQUEST = 'GET_TOP_GAME_LIST_REQUEST';
export const GET_TOP_GAME_LIST_FAIL = 'GET_TOP_GAME_LIST_FAIL';

export const GET_POPULAR_GAME_LIST_SUCCESS = 'GET_POPULAR_GAME_LIST_SUCCESS';
export const GET_POPULAR_GAME_LIST_REQUEST = 'GET_POPULAR_GAME_LIST_REQUEST';
export const GET_POPULAR_GAME_LIST_FAIL = 'GET_TOP_GAME_LIST_FAIL';

export const GET_LIVE_CASINO_GAME_LIST_SUCCESS = 'GET_LIVE_CASINO_GAME_LIST_SUCCESS';
export const GET_LIVE_CASINO_GAME_LIST_REQUEST = 'GET_LIVE_CASINO_GAME_LIST_REQUEST';
export const GET_LIVE_CASINO_GAME_LIST_FAIL = 'GET_LIVE_CASINO_GAME_LIST_FAIL';

export const GET_GAME_CATEGORY_SUCCESS = 'GET_GAME_CATEGORY_SUCCESS';
export const GET_GAME_CATEGORY_REQUEST = 'GET_GAME_CATEGORY_REQUEST';
export const GET_GAME_CATEGORY_FAIL = 'GET_GAME_CATEGORY_FAIL';

export const GET_NEW_GAME_LIST_SUCCESS = 'GET_NEW_GAME_LIST_SUCCESS';
export const GET_NEW_GAME_LIST_REQUEST = 'GET_NEW_GAME_LIST_REQUEST';
export const GET_NEW_GAME_LIST_FAIL = 'GET_NEW_GAME_LIST_FAIL';

export const GET_INSTANT_GAME_LIST_SUCCESS = 'GET_INSTANT_GAME_LIST_SUCCESS';
export const GET_INSTANT_GAME_LIST_REQUEST = 'GET_INSTANT_GAME_LIST_REQUEST';
export const GET_INSTANT_GAME_LIST_FAIL = 'GET_INSTANT_GAME_LIST_FAIL';

export const GET_TABLE_GAME_LIST_SUCCESS = 'GET_TABLE_GAME_LIST_SUCCESS';
export const GET_TABLE_GAME_LIST_REQUEST = 'GET_TABLE_GAME_LIST_REQUEST';
export const GET_TABLE_GAME_LIST_FAIL = 'GET_TABLE_GAME_LIST_FAIL';

export const GET_JACKPOT_GAME_LIST_SUCCESS = 'GET_JACKPOT_GAME_LIST_SUCCESS';
export const GET_JACKPOT_GAME_LIST_REQUEST = 'GET_JACKPOT_GAME_LIST_REQUEST';
export const GET_JACKPOT_GAME_LIST_FAIL = 'GET_JACKPOT_GAME_LIST_FAIL';

export const GET_TV_GAME_LIST_SUCCESS = 'GET_TV_GAME_LIST_SUCCESS';
export const GET_TV_GAME_LIST_REQUEST = 'GET_TV_GAME_LIST_REQUEST';
export const GET_TV_GAME_LIST_FAIL = 'GET_TV_GAME_LIST_FAIL';

export const GET_ALL_GAME_LIST_SUCCESS = 'GET_ALL_GAME_LIST_SUCCESS';
export const GET_ALL_GAME_LIST_REQUEST = 'GET_ALL_GAME_LIST_REQUEST';
export const GET_ALL_GAME_LIST_FAIL = 'GET_ALL_GAME_LIST_FAIL';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const GET_GAMES_LIKE_THIS_LIST_SUCCESS = 'GET_GAMES_LIKE_THIS_LIST_SUCCESS';
export const GET_GAMES_LIKE_THIS_LIST_REQUEST = 'GET_GAMES_LIKE_THIS_LIST_REQUEST';
export const GET_GAMES_LIKE_THIS_LIST_FAIL = 'GET_GAMES_LIKE_THIS_LIST_FAIL';

export const GET_LAST_PLAYED_GAMES_SUCCESS = 'GET_LAST_PLAYED_GAMES_SUCCESS';
export const GET_LAST_PLAYED_GAMES_REQUEST = 'GET_LAST_PLAYED_GAMES_REQUEST';
export const GET_LAST_PLAYED_GAMES_FAIL = 'GET_LAST_PLAYED_GAMES_FAIL';
