
export const GET_HOME_LIST_SUCCESS = 'GET_HOME_LIST_SUCCESS';
export const GET_HOME_LIST_REQUEST = 'GET_HOME_LIST_REQUEST';
export const GET_HOME_LIST_FAIL = 'GET_HOME_LIST_FAIL';

export const GET_HOME_BANNER_LIST_SUCCESS = 'GET_HOME_BANNER_LIST_SUCCESS';
export const GET_HOME_BANNER_LIST_REQUEST = 'GET_HOME_BANNER_LIST_REQUEST';
export const GET_HOME_BANNER_LIST_FAIL = 'GET_HOME_BANNER_LIST_FAIL';

export const GET_PROVIDER_LIST_SUCCESS = 'GET_PROVIDER_LIST_SUCCESS';
export const GET_PROVIDER_LIST_REQUEST = 'GET_PROVIDER_LIST_REQUEST';
export const GET_PROVIDER_LIST_FAIL = 'GET_PROVIDER_LIST_FAIL';

export const GET_PROVIDER_GAMES_LIST_SUCCESS = 'GET_PROVIDER_GAMES_LIST_SUCCESS';
export const GET_PROVIDER_GAMES_LIST_REQUEST = 'GET_PROVIDER_GAMES_LIST_REQUEST';
export const GET_PROVIDER_GAMES_LIST_FAIL = 'GET_PROVIDER_GAMES_LIST_FAIL';

export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';

export const GET_PROMOTIONS_LIST_SUCCESS = 'GET_PROMOTIONS_LIST_SUCCESS';
export const GET_PROMOTIONS_LIST_REQUEST = 'GET_PROMOTIONS_LIST_REQUEST';
export const GET_PROMOTIONS_LIST_FAIL = 'GET_PROMOTIONS_LIST_FAIL';

export const USER_WALLET_BALANCE_UPDATE_SUCCESS = 'USER_WALLET_BALANCE_UPDATE_SUCCESS';
export const USER_WALLET_BALANCE_UPDATE_REQUEST = 'USER_WALLET_BALANCE_UPDATE_REQUEST';
export const USER_WALLET_BALANCE_UPDATE_FAIL = 'USER_WALLET_BALANCE_UPDATE_FAIL';

export const NOTIFICATION_UPDATE_SOCKET_SUCCESS = 'NOTIFICATION_UPDATE_SOCKET_SUCCESS';
export const NOTIFICATION_UPDATE_SOCKET_REQUEST = 'NOTIFICATION_UPDATE_SOCKET_REQUEST';
export const NOTIFICATION_UPDATE_SOCKET_FAIL = 'NOTIFICATION_UPDATE_SOCKET_FAIL';


