
//Withdrawal
export const WITHDRAWAL_REQUEST = "WITHDRAWAL_REQUEST";
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_FAIL = "WITHDRAWAL_FAIL";

export const WITHDRAWAL_DETAILS_REQUEST = "WITHDRAWAL_DETAILS_REQUEST";
export const WITHDRAWAL_DETAILS_SUCCESS = "WITHDRAWAL_DETAILS_SUCCESS";
export const WITHDRAWAL_DETAILS_FAIL = "WITHDRAWAL_DETAILS_FAIL";


//Deposite
export const DEPOSITE_REQUEST = "DEPOSITE_REQUEST";
export const DEPOSITE_SUCCESS = "DEPOSITE_SUCCESS";
export const DEPOSITE_FAIL = "DEPOSITE_FAIL";

export const USER_DEPOSITE_DETAILS_REQUEST = "USER_DEPOSITE_DETAILS_REQUEST";
export const USER_DEPOSITE_DETAILS_SUCCESS = "USER_DEPOSITE_DETAILS_SUCCESS";
export const USER_DEPOSITE_DETAILS_FAIL = "USER_DEPOSITE_DETAILS_FAIL";

export const GENERATE_RANDOM_UPI_FAIL = "GENERATE_RANDOM_UPI_FAIL";
export const GENERATE_RANDOM_UPI_REQUEST = "GENERATE_RANDOM_UPI_REQUEST";
export const GENERATE_RANDOM_UPI_SUCCESS = "GENERATE_RANDOM_UPI__SUCCESS";


export const GET_PAYMENT_UPI_FAIL = "GET_PAYMENT_UPI_FAIL";
export const GET_PAYMENT_UPI_REQUEST = "GET_PAYMENT_UPI_REQUEST";
export const GET_PAYMENT_UPI_SUCCESS = "GET_PAYMENT_UPI__SUCCESS";

export const TRANSACTION_HISTORY_FAIL = "TRANSACTION_HISTORY_FAIL";
export const TRANSACTION_HISTORY_REQUEST = "TRANSACTION_HISTORY_REQUEST";
export const TRANSACTION_HISTORY_SUCCESS = "TRANSACTION_HISTORY__SUCCESS";
