import { RouteConfig } from "@/Config/CommonConfig"

export const headerList: any = [
    { name: 'SPORT', status: true, route: RouteConfig?.Home },
    { name: 'LIVE BETTING', status: false, route: RouteConfig?.Home },
    { name: 'LIVE CASINO', status: false, route: RouteConfig?.Home },
    { name: 'GAMES', status: false, route: RouteConfig?.Home },
    { name: 'PROMOTIONS', status: true, route: RouteConfig?.Promotions },
]





export const countriesAndCurrencies: any = [
    { "name": "Afghanistan", "currency_code": "AFN", "currency_name": "Afghan Afghani (AFN)", "country_code": "AF" },
    { "name": "Albania", "currency_code": "ALL", "currency_name": "Albanian Lek (ALL)", "country_code": "AL" },
    { "name": "Algeria", "currency_code": "DZD", "currency_name": "Algerian Dinar (DZD)", "country_code": "DZ" },
    { "name": "Andorra", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "AD" },
    { "name": "Angola", "currency_code": "AOA", "currency_name": "Angolan Kwanza (AOA)", "country_code": "AO" },
    { "name": "Antarctica", "currency_code": null, "currency_name": null, "country_code": "AQ" },
    { "name": "Argentina", "currency_code": "ARS", "currency_name": "Argentine Peso (ARS)", "country_code": "AR" },
    { "name": "Armenia", "currency_code": "AMD", "currency_name": "Armenian Dram (AMD)", "country_code": "AM" },
    { "name": "Aruba", "currency_code": "AWG", "currency_name": "Aruban Florin (AWG)", "country_code": "AW" },
    { "name": "Australia", "currency_code": "AUD", "currency_name": "Australian Dollar (AUD)", "country_code": "AU" },
    { "name": "Austria", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "AT" },
    { "name": "Azerbaijan", "currency_code": "AZN", "currency_name": "Azerbaijani Manat (AZN)", "country_code": "AZ" },
    { "name": "Bahamas", "currency_code": "BSD", "currency_name": "Bahamian Dollar (BSD)", "country_code": "BS" },
    { "name": "Bahrain", "currency_code": "BHD", "currency_name": "Bahraini Dinar (BHD)", "country_code": "BH" },
    { "name": "Bangladesh", "currency_code": "BDT", "currency_name": "Bangladeshi Taka (BDT)", "country_code": "BD" },
    { "name": "Barbados", "currency_code": "BBD", "currency_name": "Barbadian Dollar (BBD)", "country_code": "BB" },
    { "name": "Belarus", "currency_code": "BYN", "currency_name": "Belarusian Ruble (BYN)", "country_code": "BY" },
    { "name": "Belgium", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "BE" },
    { "name": "Belize", "currency_code": "BZD", "currency_name": "Belize Dollar (BZD)", "country_code": "BZ" },
    { "name": "Benin", "currency_code": "XOF", "currency_name": "West African CFA franc (XOF)", "country_code": "BJ" },
    { "name": "Bermuda", "currency_code": "BMD", "currency_name": "Bermudian Dollar (BMD)", "country_code": "BM" },
    { "name": "Bhutan", "currency_code": "BTN", "currency_name": "Bhutanese Ngultrum (BTN)", "country_code": "BT" },
    { "name": "Bolivia", "currency_code": "BOB", "currency_name": "Bolivian Boliviano (BOB)", "country_code": "BO" },
    { "name": "Bonaire, Sint Eustatius and Saba", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "BQ" },
    { "name": "Bosnia and Herzegovina", "currency_code": "BAM", "currency_name": "Bosnia-Herzegovina Convertible Mark (BAM)", "country_code": "BA" },
    { "name": "Botswana", "currency_code": "BWP", "currency_name": "Botswanan Pula (BWP)", "country_code": "BW" },
    { "name": "Brazil", "currency_code": "BRL", "currency_name": "Brazilian Real (BRL)", "country_code": "BR" },
    { "name": "British Indian Ocean Territory", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "IO" },
    { "name": "Brunei Darussalam", "currency_code": "BND", "currency_name": "Brunei Dollar (BND)", "country_code": "BN" },
    { "name": "Bulgaria", "currency_code": "BGN", "currency_name": "Bulgarian Lev (BGN)", "country_code": "BG" },
    { "name": "Burkina Faso", "currency_code": "XOF", "currency_name": "West African CFA franc (XOF)", "country_code": "BF" },
    { "name": "Burundi", "currency_code": "BIF", "currency_name": "Burundian Franc (BIF)", "country_code": "BI" },
    { "name": "Cambodia", "currency_code": "KHR", "currency_name": "Cambodian Riel (KHR)", "country_code": "KH" },
    { "name": "Cameroon", "currency_code": "XAF", "currency_name": "Central African CFA franc (XAF)", "country_code": "CM" },
    { "name": "Canada", "currency_code": "CAD", "currency_name": "Canadian Dollar (CAD)", "country_code": "CA" },
    { "name": "Cape Verde", "currency_code": "CVE", "currency_name": "Cape Verdean Escudo (CVE)", "country_code": "CV" },
    { "name": "Cayman Islands", "currency_code": "KYD", "currency_name": "Cayman Islands Dollar (KYD)", "country_code": "KY" },
    { "name": "Central African Republic", "currency_code": "XAF", "currency_name": "Central African CFA franc (XAF)", "country_code": "CF" },
    { "name": "Chad", "currency_code": "XAF", "currency_name": "Central African CFA franc (XAF)", "country_code": "TD" },
    { "name": "Chile", "currency_code": "CLP", "currency_name": "Chilean Peso (CLP)", "country_code": "CL" },
    { "name": "China", "currency_code": "CNY", "currency_name": "Chinese Yuan (CNY)", "country_code": "CN" },
    { "name": "Christmas Island", "currency_code": null, "currency_name": null, "country_code": "CX" },
    { "name": "Cocos (Keeling) Islands", "currency_code": null, "currency_name": null, "country_code": "CC" },
    { "name": "Colombia", "currency_code": "COP", "currency_name": "Colombian Peso (COP)", "country_code": "CO" },
    { "name": "Comoros", "currency_code": "KMF", "currency_name": "Comorian Franc (KMF)", "country_code": "KM" },
    { "name": "Congo", "currency_code": "CDF", "currency_name": "Congolese Franc (CDF)", "country_code": "CG" },
    { "name": "Congo, Democratic Republic of the", "currency_code": "CDF", "currency_name": "Congolese Franc (CDF)", "country_code": "CD" },
    { "name": "Cook Islands", "currency_code": "NZD", "currency_name": "New Zealand Dollar (NZD)", "country_code": "CK" },
    { "name": "Costa Rica", "currency_code": "CRC", "currency_name": "Costa Rican Colón (CRC)", "country_code": "CR" },
    { "name": "Côte d'Ivoire", "currency_code": "XOF", "currency_name": "West African CFA franc (XOF)", "country_code": "CI" },
    { "name": "Croatia", "currency_code": "HRK", "currency_name": "Croatian Kuna (HRK)", "country_code": "HR" },
    { "name": "Cuba", "currency_code": "CUP", "currency_name": "Cuban Peso (CUP)", "country_code": "CU" },
    { "name": "Curaçao", "currency_code": "ANG", "currency_name": "Netherlands Antillean Guilder (ANG)", "country_code": "CW" },
    { "name": "Cyprus", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "CY" },
    { "name": "Czech Republic", "currency_code": "CZK", "currency_name": "Czech Republic Koruna (CZK)", "country_code": "CZ" },
    { "name": "Denmark", "currency_code": "DKK", "currency_name": "Danish Krone (DKK)", "country_code": "DK" },
    { "name": "Djibouti", "currency_code": "DJF", "currency_name": "Djiboutian Franc (DJF)", "country_code": "DJ" },
    { "name": "Dominica", "currency_code": "XCD", "currency_name": "East Caribbean Dollar (XCD)", "country_code": "DM" },
    { "name": "Dominican Republic", "currency_code": "DOP", "currency_name": "Dominican Peso (DOP)", "country_code": "DO" },
    { "name": "Ecuador", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "EC" },
    { "name": "Egypt", "currency_code": "EGP", "currency_name": "Egyptian Pound (EGP)", "country_code": "EG" },
    { "name": "El Salvador", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "SV" },
    { "name": "Equatorial Guinea", "currency_code": "XAF", "currency_name": "Central African CFA franc (XAF)", "country_code": "GQ" },
    { "name": "Eritrea", "currency_code": "ERN", "currency_name": "Eritrean Nakfa (ERN)", "country_code": "ER" },
    { "name": "Estonia", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "EE" },
    { "name": "Ethiopia", "currency_code": "ETB", "currency_name": "Ethiopian Birr (ETB)", "country_code": "ET" },
    { "name": "Falkland Islands (Malvinas)", "currency_code": "FKP", "currency_name": "Falkland Islands Pound (FKP)", "country_code": "FK" },
    { "name": "Faroe Islands", "currency_code": "DKK", "currency_name": "Danish Krone (DKK)", "country_code": "FO" },
    { "name": "Fiji", "currency_code": "FJD", "currency_name": "Fijian Dollar (FJD)", "country_code": "FJ" },
    { "name": "Finland", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "FI" },
    { "name": "France", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "FR" },
    { "name": "French Guiana", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "GF" },
    { "name": "French Polynesia", "currency_code": "XPF", "currency_name": "CFP Franc (XPF)", "country_code": "PF" },
    { "name": "French Southern Territories", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "TF" },
    { "name": "Gabon", "currency_code": "XAF", "currency_name": "Central African CFA franc (XAF)", "country_code": "GA" },
    { "name": "Gambia", "currency_code": "GMD", "currency_name": "Gambian Dalasi (GMD)", "country_code": "GM" },
    { "name": "Georgia", "currency_code": "GEL", "currency_name": "Georgian Lari (GEL)", "country_code": "GE" },
    { "name": "Germany", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "DE" },
    { "name": "Ghana", "currency_code": "GHS", "currency_name": "Ghanaian Cedi (GHS)", "country_code": "GH" },
    { "name": "Gibraltar", "currency_code": "GIP", "currency_name": "Gibraltar Pound (GIP)", "country_code": "GI" },
    { "name": "Greece", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "GR" },
    { "name": "Greenland", "currency_code": "DKK", "currency_name": "Danish Krone (DKK)", "country_code": "GL" },
    { "name": "Grenada", "currency_code": "XCD", "currency_name": "East Caribbean Dollar (XCD)", "country_code": "GD" },
    { "name": "Guadeloupe", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "GP" },
    { "name": "Guam", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "GU" },
    { "name": "Guatemala", "currency_code": "GTQ", "currency_name": "Guatemalan Quetzal (GTQ)", "country_code": "GT" },
    { "name": "Guernsey", "currency_code": "GBP", "currency_name": "British Pound Sterling (GBP)", "country_code": "GG" },
    { "name": "Guinea", "currency_code": "GNF", "currency_name": "Guinean Franc (GNF)", "country_code": "GN" },
    { "name": "Guinea-Bissau", "currency_code": "XOF", "currency_name": "West African CFA franc (XOF)", "country_code": "GW" },
    { "name": "Guyana", "currency_code": "GYD", "currency_name": "Guyanaese Dollar (GYD)", "country_code": "GY" },
    { "name": "Haiti", "currency_code": "HTG", "currency_name": "Haitian Gourde (HTG)", "country_code": "HT" },
    { "name": "Heard Island and McDonald Islands", "currency_code": null, "currency_name": null, "country_code": "HM" },
    { "name": "Holy See (Vatican City State)", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "VA" },
    { "name": "Honduras", "currency_code": "HNL", "currency_name": "Honduran Lempira (HNL)", "country_code": "HN" },
    { "name": "Hong Kong", "currency_code": "HKD", "currency_name": "Hong Kong Dollar (HKD)", "country_code": "HK" },
    { "name": "Hungary", "currency_code": "HUF", "currency_name": "Hungarian Forint (HUF)", "country_code": "HU" },
    { "name": "Iceland", "currency_code": "ISK", "currency_name": "Icelandic Króna (ISK)", "country_code": "IS" },
    { "name": "India", "currency_code": "INR", "currency_name": "Indian Rupee (INR)", "country_code": "IN" },
    { "name": "Indonesia", "currency_code": "IDR", "currency_name": "Indonesian Rupiah (IDR)", "country_code": "ID" },
    { "name": "Iran, Islamic Republic of", "currency_code": "IRR", "currency_name": "Iranian Rial (IRR)", "country_code": "IR" },
    { "name": "Iraq", "currency_code": "IQD", "currency_name": "Iraqi Dinar (IQD)", "country_code": "IQ" },
    { "name": "Ireland", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "IE" },
    { "name": "Isle of Man", "currency_code": "GBP", "currency_name": "British Pound Sterling (GBP)", "country_code": "IM" },
    { "name": "Israel", "currency_code": "ILS", "currency_name": "Israeli New Sheqel (ILS)", "country_code": "IL" },
    { "name": "Italy", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "IT" },
    { "name": "Jamaica", "currency_code": "JMD", "currency_name": "Jamaican Dollar (JMD)", "country_code": "JM" },
    { "name": "Japan", "currency_code": "JPY", "currency_name": "Japanese Yen (JPY)", "country_code": "JP" },
    { "name": "Jersey", "currency_code": "GBP", "currency_name": "British Pound Sterling (GBP)", "country_code": "JE" },
    { "name": "Jordan", "currency_code": "JOD", "currency_name": "Jordanian Dinar (JOD)", "country_code": "JO" },
    { "name": "Kazakhstan", "currency_code": "KZT", "currency_name": "Kazakhstani Tenge (KZT)", "country_code": "KZ" },
    { "name": "Kenya", "currency_code": "KES", "currency_name": "Kenyan Shilling (KES)", "country_code": "KE" },
    { "name": "Kiribati", "currency_code": "AUD", "currency_name": "Australian Dollar (AUD)", "country_code": "KI" },
    { "name": "Korea, Democratic People's Republic of", "currency_code": "KPW", "currency_name": "North Korean Won (KPW)", "country_code": "KP" },
    { "name": "Korea, Republic of", "currency_code": "KRW", "currency_name": "South Korean Won (KRW)", "country_code": "KR" },
    { "name": "Kosovo", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "XK" },
    { "name": "Kuwait", "currency_code": "KWD", "currency_name": "Kuwaiti Dinar (KWD)", "country_code": "KW" },
    { "name": "Kyrgyzstan", "currency_code": "KGS", "currency_name": "Kyrgystani Som (KGS)", "country_code": "KG" },
    { "name": "Lao People's Democratic Republic", "currency_code": "LAK", "currency_name": "Laotian Kip (LAK)", "country_code": "LA" },
    { "name": "Latvia", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "LV" },
    { "name": "Lebanon", "currency_code": "LBP", "currency_name": "Lebanese Pound (LBP)", "country_code": "LB" },
    { "name": "Lesotho", "currency_code": "LSL", "currency_name": "Lesotho Loti (LSL)", "country_code": "LS" },
    { "name": "Liberia", "currency_code": "LRD", "currency_name": "Liberian Dollar (LRD)", "country_code": "LR" },
    { "name": "Libya", "currency_code": "LYD", "currency_name": "Libyan Dinar (LYD)", "country_code": "LY" },
    { "name": "Liechtenstein", "currency_code": "CHF", "currency_name": "Swiss Franc (CHF)", "country_code": "LI" },
    { "name": "Lithuania", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "LT" },
    { "name": "Luxembourg", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "LU" },
    { "name": "Macao", "currency_code": "MOP", "currency_name": "Macanese Pataca (MOP)", "country_code": "MO" },
    { "name": "Macedonia, the Former Yugoslav Republic of", "currency_code": "MKD", "currency_name": "Macedonian Denar (MKD)", "country_code": "MK" },
    { "name": "Madagascar", "currency_code": "MGA", "currency_name": "Malagasy Ariary (MGA)", "country_code": "MG" },
    { "name": "Malawi", "currency_code": "MWK", "currency_name": "Malawian Kwacha (MWK)", "country_code": "MW" },
    { "name": "Malaysia", "currency_code": "MYR", "currency_name": "Malaysian Ringgit (MYR)", "country_code": "MY" },
    { "name": "Maldives", "currency_code": "MVR", "currency_name": "Maldivian Rufiyaa (MVR)", "country_code": "MV" },
    { "name": "Mali", "currency_code": "XOF", "currency_name": "West African CFA franc (XOF)", "country_code": "ML" },
    { "name": "Malta", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "MT" },
    { "name": "Marshall Islands", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "MH" },
    { "name": "Martinique", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "MQ" },
    { "name": "Mauritania", "currency_code": "MRU", "currency_name": "Mauritanian Ouguiya (MRU)", "country_code": "MR" },
    { "name": "Mauritius", "currency_code": "MUR", "currency_name": "Mauritian Rupee (MUR)", "country_code": "MU" },
    { "name": "Mayotte", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "YT" },
    { "name": "Mexico", "currency_code": "MXN", "currency_name": "Mexican Peso (MXN)", "country_code": "MX" },
    { "name": "Micronesia, Federated States of", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "FM" },
    { "name": "Moldova, Republic of", "currency_code": "MDL", "currency_name": "Moldovan Leu (MDL)", "country_code": "MD" },
    { "name": "Monaco", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "MC" },
    { "name": "Mongolia", "currency_code": "MNT", "currency_name": "Mongolian Tugrik (MNT)", "country_code": "MN" },
    { "name": "Montenegro", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "ME" },
    { "name": "Montserrat", "currency_code": "XCD", "currency_name": "East Caribbean Dollar (XCD)", "country_code": "MS" },
    { "name": "Morocco", "currency_code": "MAD", "currency_name": "Moroccan Dirham (MAD)", "country_code": "MA" },
    { "name": "Mozambique", "currency_code": "MZN", "currency_name": "Mozambican Metical (MZN)", "country_code": "MZ" },
    { "name": "Myanmar", "currency_code": "MMK", "currency_name": "Myanmar Kyat (MMK)", "country_code": "MM" },
    { "name": "Namibia", "currency_code": "NAD", "currency_name": "Namibian Dollar (NAD)", "country_code": "NA" },
    { "name": "Nauru", "currency_code": "AUD", "currency_name": "Australian Dollar (AUD)", "country_code": "NR" },
    { "name": "Nepal", "currency_code": "NPR", "currency_name": "Nepalese Rupee (NPR)", "country_code": "NP" },
    { "name": "Netherlands", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "NL" },
    { "name": "New Caledonia", "currency_code": "XPF", "currency_name": "CFP Franc (XPF)", "country_code": "NC" },
    { "name": "New Zealand", "currency_code": "NZD", "currency_name": "New Zealand Dollar (NZD)", "country_code": "NZ" },
    { "name": "Nicaragua", "currency_code": "NIO", "currency_name": "Nicaraguan Córdoba (NIO)", "country_code": "NI" },
    { "name": "Niger", "currency_code": "XOF", "currency_name": "West African CFA franc (XOF)", "country_code": "NE" },
    { "name": "Nigeria", "currency_code": "NGN", "currency_name": "Nigerian Naira (NGN)", "country_code": "NG" },
    { "name": "Niue", "currency_code": "NZD", "currency_name": "New Zealand Dollar (NZD)", "country_code": "NU" },
    { "name": "Norfolk Island", "currency_code": "AUD", "currency_name": "Australian Dollar (AUD)", "country_code": "NF" },
    { "name": "Northern Mariana Islands", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "MP" },
    { "name": "Norway", "currency_code": "NOK", "currency_name": "Norwegian Krone (NOK)", "country_code": "NO" },
    { "name": "Oman", "currency_code": "OMR", "currency_name": "Omani Rial (OMR)", "country_code": "OM" },
    { "name": "Pakistan", "currency_code": "PKR", "currency_name": "Pakistani Rupee (PKR)", "country_code": "PK" },
    { "name": "Palau", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "PW" },
    { "name": "Palestine, State of", "currency_code": "ILS", "currency_name": "Israeli New Sheqel (ILS)", "country_code": "PS" },
    { "name": "Panama", "currency_code": "PAB", "currency_name": "Panamanian Balboa (PAB)", "country_code": "PA" },
    { "name": "Papua New Guinea", "currency_code": "PGK", "currency_name": "Papua New Guinean Kina (PGK)", "country_code": "PG" },
    { "name": "Paraguay", "currency_code": "PYG", "currency_name": "Paraguayan Guarani (PYG)", "country_code": "PY" },
    { "name": "Peru", "currency_code": "PEN", "currency_name": "Peruvian Nuevo Sol (PEN)", "country_code": "PE" },
    { "name": "Philippines", "currency_code": "PHP", "currency_name": "Philippine Peso (PHP)", "country_code": "PH" },
    { "name": "Pitcairn", "currency_code": null, "currency_name": null, "country_code": "PN" },
    { "name": "Poland", "currency_code": "PLN", "currency_name": "Polish Zloty (PLN)", "country_code": "PL" },
    { "name": "Portugal", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "PT" },
    { "name": "Puerto Rico", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "PR" },
    { "name": "Qatar", "currency_code": "QAR", "currency_name": "Qatari Rial (QAR)", "country_code": "QA" },
    { "name": "Réunion", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "RE" },
    { "name": "Romania", "currency_code": "RON", "currency_name": "Romanian Leu (RON)", "country_code": "RO" },
    { "name": "Russian Federation", "currency_code": "RUB", "currency_name": "Russian Ruble (RUB)", "country_code": "RU" },
    { "name": "Rwanda", "currency_code": "RWF", "currency_name": "Rwandan Franc (RWF)", "country_code": "RW" },
    { "name": "Saint Barthélemy", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "BL" },
    { "name": "Saint Helena, Ascension and Tristan da Cunha", "currency_code": "SHP", "currency_name": "Saint Helena Pound (SHP)", "country_code": "SH" },
    { "name": "Saint Kitts and Nevis", "currency_code": "XCD", "currency_name": "East Caribbean Dollar (XCD)", "country_code": "KN" },
    { "name": "Saint Lucia", "currency_code": "XCD", "currency_name": "East Caribbean Dollar (XCD)", "country_code": "LC" },
    { "name": "Saint Martin (French part)", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "MF" },
    { "name": "Saint Pierre and Miquelon", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "PM" },
    { "name": "Saint Vincent and the Grenadines", "currency_code": "XCD", "currency_name": "East Caribbean Dollar (XCD)", "country_code": "VC" },
    { "name": "Samoa", "currency_code": "WST", "currency_name": "Samoan Tala (WST)", "country_code": "WS" },
    { "name": "San Marino", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "SM" },
    { "name": "Sao Tome and Principe", "currency_code": "STN", "currency_name": "São Tomé and Príncipe Dobra (STN)", "country_code": "ST" },
    { "name": "Saudi Arabia", "currency_code": "SAR", "currency_name": "Saudi Riyal (SAR)", "country_code": "SA" },
    { "name": "Senegal", "currency_code": "XOF", "currency_name": "West African CFA franc (XOF)", "country_code": "SN" },
    { "name": "Serbia", "currency_code": "RSD", "currency_name": "Serbian Dinar (RSD)", "country_code": "RS" },
    { "name": "Seychelles", "currency_code": "SCR", "currency_name": "Seychellois Rupee (SCR)", "country_code": "SC" },
    { "name": "Sierra Leone", "currency_code": "SLL", "currency_name": "Sierra Leonean Leone (SLL)", "country_code": "SL" },
    { "name": "Singapore", "currency_code": "SGD", "currency_name": "Singapore Dollar (SGD)", "country_code": "SG" },
    { "name": "Sint Maarten (Dutch part)", "currency_code": "ANG", "currency_name": "Netherlands Antillean Guilder (ANG)", "country_code": "SX" },
    { "name": "Slovakia", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "SK" },
    { "name": "Slovenia", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "SI" },
    { "name": "Solomon Islands", "currency_code": "SBD", "currency_name": "Solomon Islands Dollar (SBD)", "country_code": "SB" },
    { "name": "Somalia", "currency_code": "SOS", "currency_name": "Somali Shilling (SOS)", "country_code": "SO" },
    { "name": "South Africa", "currency_code": "ZAR", "currency_name": "South African Rand (ZAR)", "country_code": "ZA" },
    { "name": "South Georgia and the South Sandwich Islands", "currency_code": "GBP", "currency_name": "British Pound Sterling (GBP)", "country_code": "GS" },
    { "name": "South Sudan", "currency_code": "SSP", "currency_name": "South Sudanese Pound (SSP)", "country_code": "SS" },
    { "name": "Spain", "currency_code": "EUR", "currency_name": "Euro (EUR)", "country_code": "ES" },
    { "name": "Sri Lanka", "currency_code": "LKR", "currency_name": "Sri Lankan Rupee (LKR)", "country_code": "LK" },
    { "name": "Sudan", "currency_code": "SDG", "currency_name": "Sudanese Pound (SDG)", "country_code": "SD" },
    { "name": "Suriname", "currency_code": "SRD", "currency_name": "Surinamese Dollar (SRD)", "country_code": "SR" },
    { "name": "Svalbard and Jan Mayen", "currency_code": "NOK", "currency_name": "Norwegian Krone (NOK)", "country_code": "SJ" },
    { "name": "Swaziland", "currency_code": "SZL", "currency_name": "Swazi Lilangeni (SZL)", "country_code": "SZ" },
    { "name": "Sweden", "currency_code": "SEK", "currency_name": "Swedish Krona (SEK)", "country_code": "SE" },
    { "name": "Switzerland", "currency_code": "CHF", "currency_name": "Swiss Franc (CHF)", "country_code": "CH" },
    { "name": "Syrian Arab Republic", "currency_code": "SYP", "currency_name": "Syrian Pound (SYP)", "country_code": "SY" },
    { "name": "Taiwan, Province of China", "currency_code": "TWD", "currency_name": "New Taiwan Dollar (TWD)", "country_code": "TW" },
    { "name": "Tajikistan", "currency_code": "TJS", "currency_name": "Tajikistani Somoni (TJS)", "country_code": "TJ" },
    { "name": "Tanzania, United Republic of", "currency_code": "TZS", "currency_name": "Tanzanian Shilling (TZS)", "country_code": "TZ" },
    { "name": "Thailand", "currency_code": "THB", "currency_name": "Thai Baht (THB)", "country_code": "TH" },
    { "name": "Timor-Leste", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "TL" },
    { "name": "Togo", "currency_code": "XOF", "currency_name": "West African CFA franc (XOF)", "country_code": "TG" },
    { "name": "Tokelau", "currency_code": "NZD", "currency_name": "New Zealand Dollar (NZD)", "country_code": "TK" },
    { "name": "Tonga", "currency_code": "TOP", "currency_name": "Tongan Pa'anga (TOP)", "country_code": "TO" },
    { "name": "Trinidad and Tobago", "currency_code": "TTD", "currency_name": "Trinidad and Tobago Dollar (TTD)", "country_code": "TT" },
    { "name": "Tunisia", "currency_code": "TND", "currency_name": "Tunisian Dinar (TND)", "country_code": "TN" },
    { "name": "Turkey", "currency_code": "TRY", "currency_name": "Turkish Lira (TRY)", "country_code": "TR" },
    { "name": "Turkmenistan", "currency_code": "TMT", "currency_name": "Turkmenistani Manat (TMT)", "country_code": "TM" },
    { "name": "Turks and Caicos Islands", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "TC" },
    { "name": "Tuvalu", "currency_code": "AUD", "currency_name": "Australian Dollar (AUD)", "country_code": "TV" },
    { "name": "Uganda", "currency_code": "UGX", "currency_name": "Ugandan Shilling (UGX)", "country_code": "UG" },
    { "name": "Ukraine", "currency_code": "UAH", "currency_name": "Ukrainian Hryvnia (UAH)", "country_code": "UA" },
    { "name": "United Arab Emirates", "currency_code": "AED", "currency_name": "United Arab Emirates Dirham (AED)", "country_code": "AE" },
    { "name": "United Kingdom", "currency_code": "GBP", "currency_name": "British Pound Sterling (GBP)", "country_code": "GB" },
    { "name": "United States", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "US" },
    { "name": "United States Minor Outlying Islands", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "UM" },
    { "name": "Uruguay", "currency_code": "UYU", "currency_name": "Uruguayan Peso (UYU)", "country_code": "UY" },
    { "name": "Uzbekistan", "currency_code": "UZS", "currency_name": "Uzbekistan Som (UZS)", "country_code": "UZ" },
    { "name": "Vanuatu", "currency_code": "VUV", "currency_name": "Vanuatu Vatu (VUV)", "country_code": "VU" },
    { "name": "Venezuela, Bolivarian Republic of", "currency_code": "VES", "currency_name": "Venezuelan Bolívar (VES)", "country_code": "VE" },
    { "name": "Viet Nam", "currency_code": "VND", "currency_name": "Vietnamese Dong (VND)", "country_code": "VN" },
    { "name": "Virgin Islands, British", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "VG" },
    { "name": "Virgin Islands, U.S.", "currency_code": "USD", "currency_name": "United States Dollar (USD)", "country_code": "VI" },
    { "name": "Wallis and Futuna", "currency_code": "XPF", "currency_name": "CFP Franc (XPF)", "country_code": "WF" },
    { "name": "Western Sahara", "currency_code": "MAD", "currency_name": "Moroccan Dirham (MAD)", "country_code": "EH" },
    { "name": "Yemen", "currency_code": "YER", "currency_name": "Yemeni Rial (YER)", "country_code": "YE" },
    { "name": "Zambia", "currency_code": "ZMW", "currency_name": "Zambian Kwacha (ZMW)", "country_code": "ZM" },
    { "name": "Zimbabwe", "currency_code": "ZWL", "currency_name": "Zimbabwean Dollar (ZWL)", "country_code": "ZW" }
]
